# Generated by Django 4.2.7 on 2023-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_company_contact_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
