# Generated by Django 4.2.7 on 2023-12-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='full_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
