# Generated by Django 4.2.7 on 2023-12-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_selectedcontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='Null', max_length=50)),
                ('last_name', models.CharField(default='Null', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('title', models.CharField(default='No Title', max_length=100)),
                ('company', models.CharField(default='No Company', max_length=100)),
                ('type', models.CharField(default='None', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('level', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='contacts.campaign'),
        ),
    ]
