# Generated by Django 4.2.7 on 2023-12-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_campaign_contact_campaigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='company',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='email',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='level',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='location',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='type',
        ),
        migrations.CreateModel(
            name='CampaignB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_b', to='contacts.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_a', to='contacts.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='campaign_a_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_a', to='contacts.campaigna'),
        ),
        migrations.AddField(
            model_name='contact',
            name='campaign_b_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_b', to='contacts.campaignb'),
        ),
    ]
