# Generated by Django 4.2.7 on 2023-12-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_remove_campaign_company_remove_campaign_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.CharField(default='No Company', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email',
            field=models.EmailField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='first_name',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_name',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='level',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='phone',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='No Title', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
