# Generated by Django 4.2.7 on 2023-12-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_remove_campaign_name_campaign_company_campaign_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigna',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignb',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='campaign_a_info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='campaign_b_info',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='campaigns',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignA',
        ),
        migrations.DeleteModel(
            name='CampaignB',
        ),
    ]
