# Generated by Django 4.2.7 on 2023-12-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_campaign_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
