# Generated by Django 4.2.7 on 2023-12-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_campaign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='Campaign_Emails',
        ),
    ]
