# Generated by Django 4.2.7 on 2023-12-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_campaign_emails_campaign_name_campaign_emails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_emails',
            name='company',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_emails',
            name='first_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_emails',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_emails',
            name='location',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_emails',
            name='title',
            field=models.CharField(default='No Title', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_emails',
            name='type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
