# Generated by Django 4.2.7 on 2023-12-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_campaign_emails_company_campaign_emails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign_emails',
            name='campaign_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign_emails',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign_emails',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign_emails',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign_emails',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign_emails',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
