# Generated by Django 4.2.7 on 2024-01-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_campaign_delete_campaign_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': [('view_all_campaigns', 'Can view all campaigns')]},
        ),
    ]
