# Generated by Django 4.2.7 on 2024-01-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
