# Generated by Django 4.2.7 on 2024-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0031_contact_linkedin_alter_campaign_emails_campaign_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='university',
            field=models.CharField(default='', max_length=200),
        ),
    ]
