# Generated by Django 4.2.7 on 2024-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_contact_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('email_content1', models.TextField()),
                ('email_content2', models.TextField()),
                ('email_content3', models.TextField()),
            ],
        ),
    ]
