# Generated by Django 4.2.7 on 2024-01-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='campaign_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
