# Generated by Django 4.2.7 on 2024-01-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0041_email_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='font_family',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='email',
            name='font_size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='email',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_italics',
            field=models.BooleanField(default=False),
        ),
    ]
