# Generated by Django 4.2.7 on 2024-01-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0043_alter_email_font_family_alter_email_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_bold',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_italics',
        ),
    ]
