# Generated by Django 4.2.7 on 2024-01-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0044_remove_email_is_bold_remove_email_is_italics'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_emails',
            name='university',
            field=models.CharField(default='', max_length=200),
        ),
    ]
