# Generated by Django 4.2.7 on 2024-02-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0048_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
