# Generated by Django 4.2.7 on 2024-10-29 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0051_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='emails_sent_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='daily_limit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='max_interval',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='min_interval',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
